images:
  airflow:
    repository: my-dags
    tag: ~
    digest: ~
    pullPolicy: IfNotPresent

config:
  core:
    hostname_callable: airflow.utils.net.get_host_ip_address
dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/Hossam-Amer/DataBricks-Airflow-SocialMedial.git
    branch: Main
    rev: HEAD
    # The git revision (branch, tag, or hash) to check out, v4 only
    ref: v2-2-stable
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"
    credentialsSecret: git-credentials
